### ISSUE TITLE
Maybe you can try to optimize the code

### ISSUE THREAD

**Issue by Scyllaly** [dabasanta/DNSExplorer#1]
when i try this domain : cmbchina.com

The script will be in the state of suspended animation. Do you want to consider saving the results in a local file, such as. txt (introducing the local cache mechanism), and eliminate duplicate records, and then ping the results url or detect the url's corresponding http code according to the duplicate removal.

**Comment by dabasanta** [comment]
Scyllaly, my friend, I hope everything is going well.

Please find the new version of the DNSExplorer.sh file, which has the functionality to search for web servers in the results obtained.
Following your advice the results of different operations such as dictionary attack and crt.sh enumeration are now saved in files for easy filtering and manipulation of the data.

I have tested it with the domain in question, for domains like this it will certainly take a little longer, however, it will work fine while performing other activities while the script is running in the background.

Finally, a folder called <domain.out> is now created where important files resulting from the execution of the script are stored. The most interesting one for you being the .webservers file, I guess.

I still have to update the DNSExplorer-minimal.sh file, README file, the README images and document the functionality, however, you will be able to work with the script without any problems for now.

I hope that the new updates will meet your most urgent needs.

Without further ado, success and thanks for your input.

Best regards.
